name:               "Manjeet Dahiya"

baseurl:            ""
permalink:          /:year/:month/:day/:title/
permalink:          /:collection/:title/

markdown:           kramdown

sass:
    #style:            :compressed

# seo tags
url:    "http://manjeetdahiya.com"
author: "Manjeet Dahiya"
twitter:
  username: manjeetdahiya

social:
  name: Manjeet Dahiya
  links:
    - https://twitter.com/manjeetdahiya
    - https://www.facebook.com/manjeetdahiya
    - https://www.linkedin.com/in/manjeetdahiya
    - https://github.com/manjeetdahiya

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
