name:               "Manjeet Dahiya"

baseurl:            ""
permalink:          /:year/:month/:day/:title/
permalink:          /:collection/:title/

markdown:           kramdown

sass:
    #style:            :compressed

